# Generated by Django 6.0.2 on 2026-02-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Fuqaro'), ('SECRETARY', 'Kotib'), ('MANAGER', 'Rais'), ('REVIEWER', 'Tahrizchi'), ('SUPERADMIN', 'Admin')], default='CITIZEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'external_id', 'phone'], name='accounts_us_role_492b5a_idx'),
        ),
    ]
