# Generated by Django 6.0.2 on 2026-02-16 05:55

import apps.accounts.models
from django.db import migrations, models


def populate_missing_and_duplicate_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    manager = User._base_manager
    used_emails = set(
        email.lower()
        for email in manager.exclude(email__isnull=True).exclude(email='').values_list('email', flat=True)
    )

    for user in manager.all().order_by('id'):
        current_email = (user.email or '').strip().lower()
        if current_email and current_email not in used_emails:
            used_emails.add(current_email)
            if user.email != current_email:
                user.email = current_email
                user.save(update_fields=['email'])
            continue

        base_local = (getattr(user, 'username', '') or f'user{user.id}').strip().lower()
        if not base_local:
            base_local = f'user{user.id}'
        base_local = ''.join(ch if ch.isalnum() or ch in '._-' else '_' for ch in base_local)

        i = 0
        while True:
            suffix = f"_{i}" if i else ''
            candidate = f"{base_local}{suffix}@local.uzswlu"
            if candidate not in used_emails:
                used_emails.add(candidate)
                user.email = candidate
                user.save(update_fields=['email'])
                break
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_user_accounts_us_role_492b5a_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.RunPython(populate_missing_and_duplicate_emails, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email manzil'),
        ),
    ]
