# Generated by Django 6.0.2 on 2026-02-16 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_username_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_492b5a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +998XXXXXXXXX', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam formati: +998XXXXXXXXX (12 ta raqam)', regex='^\\+998[0-9]{9}$')]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['external_id'], name='accounts_us_externa_a0e508_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'deleted_at'], name='accounts_us_is_acti_ff227c_idx'),
        ),
    ]
