# Generated by Django 6.0.2 on 2026-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_accounts_us_role_492b5a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Fuqaro'), ('SECRETARY', 'Kotib'), ('MANAGER', 'Rais'), ('SUPERADMIN', 'Admin')], default='CITIZEN', max_length=20),
        ),
    ]
