# Generated by Django 6.0.2 on 2026-02-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('OPTIONS', 'Options'), ('HEAD', 'Head')], max_length=10, verbose_name='HTTP Metod')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name="URL yo'l")),
                ('query_params', models.TextField(blank=True, default='', verbose_name='Query parametrlar')),
                ('request_body', models.TextField(blank=True, default='', verbose_name="So'rov tanasi")),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Javob kodi')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='Javob tanasi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "API So'rov Logi",
                'verbose_name_plural': "API So'rov Loglari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'path'], name='core_apireq_method_407b90_idx'), models.Index(fields=['user', '-created_at'], name='core_apireq_user_id_5fb2d3_idx'), models.Index(fields=['response_status'], name='core_apireq_respons_5ce0b7_idx')],
            },
        ),
    ]
