# Generated by Django 6.0.2 on 2026-02-12 08:45

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Soha nomi')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.category', verbose_name='Yuqori soha')),
            ],
            options={
                'verbose_name': 'Soha',
                'verbose_name_plural': 'Sohalar',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='PDF Hujjat')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('PENDING', "Yo'naltirildi"), ('UNDER_REVIEW', 'Tahrizda'), ('REVIEWED', 'Tahrizlandi'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Qaytarildi')], default='NEW', max_length=20, verbose_name='Holati')),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan tahrizchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.category', verbose_name='Soha')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_documents', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review_file', models.FileField(upload_to='reviews/%Y/%m/%d/', verbose_name='Tahriz PDF')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Ball')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='documents.document', verbose_name='Hujjat')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Tahrizchi')),
            ],
            options={
                'verbose_name': 'Tahriz',
                'verbose_name_plural': 'Tahrizlar',
            },
        ),
    ]
