# Generated by Django 6.0.2 on 2026-02-17 05:23

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[apps.core.validators.validate_document_file], verbose_name='PDF Hujjat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_file',
            field=models.FileField(upload_to='reviews/%Y/%m/%d/', validators=[apps.core.validators.validate_review_file], verbose_name='Tahriz PDF'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ball (0-100)'),
        ),
    ]
