# Generated by Django 6.0.2 on 2026-02-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_alter_review_review_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hujjat', 'verbose_name_plural': 'Hujjatlar'},
        ),
    ]
