# Generated by Django 6.0.2 on 2026-02-17 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='assigned_reviewer',
        ),
        migrations.AlterField(
            model_name='review',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document', verbose_name='Hujjat'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('document', 'reviewer')},
        ),
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Kim biriktirdi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document', verbose_name='Hujjat')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Tahrizchi')),
            ],
            options={
                'verbose_name': 'Hujjat biriktirmasi',
                'verbose_name_plural': 'Hujjat biriktirmalari',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'reviewer')},
            },
        ),
    ]
