# Generated by Django 6.0.2 on 2026-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_assigned_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('PENDING', "Yo'naltirildi"), ('UNDER_REVIEW', 'Tahrizda'), ('REVIEWED', 'Tahrizlandi'), ('WAITING_FOR_DISPATCH', 'Yuborish kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Qaytarildi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
