# Generated by Django 6.0.2 on 2026-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='manager_decision',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi')], default='PENDING', max_length=20, verbose_name='Rais qarori'),
        ),
    ]
