# Generated by Django 6.0.2 on 2026-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentassignment_manager_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name="Ko'rildi"),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='is_seen_by_reviewer',
            field=models.BooleanField(default=False, verbose_name="Tahrizchi ko'rganmi"),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='documentassignment',
            name='manager_decision',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi')], default='PENDING', max_length=20, verbose_name='Qaror (Rais/Kotib)'),
        ),
    ]
