# Generated by Django 6.0.2 on 2026-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='is_seen_by_manager',
            field=models.BooleanField(default=False, verbose_name="Rais/Kotib ko'rganmi"),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('SEEN', "Ko'rildi"), ('PENDING', "Yo'naltirildi"), ('UNDER_REVIEW', 'Tahrizda'), ('REVIEWED', 'Tahrizlandi'), ('WAITING_FOR_DISPATCH', 'Yuborish kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Qaytarildi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
