# Generated by Django 6.0.2 on 2026-03-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_documentassignment_manager_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('DOCUMENT_SUBMITTED', 'Hujjat yuborildi'), ('NEW_DOCUMENT', 'Yangi hujjat'), ('REVIEWER_ASSIGNED', 'Tahrizchi biriktirildi'), ('REVIEW_STARTED', 'Tahriz boshlandi'), ('REVIEW_SUBMITTED', 'Tahriz yuklandi'), ('DOCUMENT_APPROVED', 'Tasdiqlandi'), ('DOCUMENT_REJECTED', 'Rad etildi'), ('REVIEW_ACCEPTED', 'Tahriz qabul qilindi'), ('REVIEW_REJECTED', 'Tahriz rad etildi'), ('DOCUMENT_DISPATCHED', 'Yuborildi')], max_length=30, verbose_name='Turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document', verbose_name='Hujjat')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
